services:

  db:
    image: postgres:alpine
    container_name: icx-postgres
    environment:
      POSTGRES_USER: icx_user
      POSTGRES_PASSWORD: icx_password
      POSTGRES_DB: icx_db
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    container_name: icx-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@icx.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - db

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: icx-backend
    environment:
      DB_HOST: db
      DB_USER: icx_user
      DB_PASSWORD: icx_password
      DB_NAME: icx_db
      PORT: 5001
    ports:
      - "5001:5001"
    volumes:
      - ./backend:/app
    depends_on:
      - db

  frontend-web:
    build:
      context: ./innovacioncomercialx-frontend-web/frontend-web
      dockerfile: Dockerfile
      target: dev
    container_name: icx-frontend-web
    ports:
      - "5173:5173"
    volumes:
      - ./innovacioncomercialx-frontend-web/frontend-web:/app
    depends_on:
      - backend

volumes:
  db-data:
